/**
 * Ticket as returned by the API (`Ticket` entity of the backend).
 *
 * `status` mirrors the `TicketStatus` enum: `OPEN`, `IN_PROGRESS` or `CLOSED`.
 * `solution` is `null` until the ticket is solved by an agent.
 */
export interface Ticket {
  /** UUID generated by the backend. */
  id: string;
  title: string;
  description: string;
  status: 'OPEN' | 'IN_PROGRESS' | 'CLOSED';
  solution: string | null;
}

/**
 * Payload required to create a ticket: same shape as `Ticket` minus the
 * server-managed fields (id, status, solution). Mirrors the `TicketRequestDto`
 * of the backend.
 */
export type CreateTicketInput = Omit<Ticket, 'id' | 'status' | 'solution'>;
